"""add actors model

Revision ID: 906a06427c29
Revises: 0c219001ed4e
Create Date: 2021-04-11 20:24:02.180461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906a06427c29'
down_revision = '0c219001ed4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actors')
    # ### end Alembic commands ###
